[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "pytest-suggest"
version = "0.0.0"
authors = [{ name = "Davide Canton", email = "davide.canton5@gmail.com" }]
description = "A pytest plugin to suggest test cases"
readme = "README.md"
dependencies = ["pytest>=8.0.0", "orjson>=3.10.7"]
requires-python = ">=3.9"

[project.scripts]
pytest-suggest = "pytest_suggest.cli.suggest:main"

[tool.setuptools.package-data]
"*" = ["*.bash", "*.ps1", "py.typed"]

[project.entry-points."pytest11"]
suggest = "pytest_suggest.plugin"

[tool.pytest.ini_options]
addopts = "--cov-report=html --cov-report=term --no-cov-on-fail -ra --import-mode=importlib"
pythonpath = ["src"]
markers = ["slow: mark test as slow"]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.html]
directory = "coverage"

[tool.pyright]
typeCheckingMode = "standard"
reportMissingTypeArgument = "error"

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "pdbp>=1.6.1",
    "pyright>=1.1.400",
    "pytest-cov>=5.0.0",
    "ruff>=0.10.0",
    "tox>=4.24.2",
]
